services:
  db:
    image: rrailee/energopgdb:latest
    container_name: Energopgdb1
    environment:
      POSTGRES_USER: EnergoDetal
      POSTGRES_PASSWORD: EnergoDetal
      POSTGRES_DB: EnergoDetal
    ports:
      - "5432:5432"
